[project]
name = "shinylive-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.1",
    "pillow==12.1.0",
    "seaborn>=0.13.2",
    "shiny>=1.5.1",
    "shinylive>=0.8.5",
]
